# Generated by Django 5.2.5 on 2025-10-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
    ]
