# Generated by Django 5.2.5 on 2025-10-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObraArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('artista', models.CharField(max_length=150, verbose_name='Artista')),
                ('year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Año')),
                ('tecnica', models.CharField(max_length=200, verbose_name='Técnica')),
                ('dimensiones', models.CharField(max_length=100, verbose_name='Dimensiones')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='obras/', verbose_name='Imagen de la Obra')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra de Arte',
                'verbose_name_plural': 'Obras de Arte',
                'ordering': ['-created'],
            },
        ),
    ]
